sonar.organization=class83108
sonar.projectKey=class83108_PersoChattai

sonar.projectName=PersoChattai
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
