"""NLP 量化指標計算。"""

from __future__ import annotations

import re

import spacy
from lexical_diversity import lex_div
from spacy.language import Language

from persochattai.assessment.schemas import NlpMetrics

_MIN_TOKENS_FOR_DIVERSITY = 50

_SELF_CORRECTION_PATTERNS = [
    r'\bi mean\b',
    r'\bno wait\b',
    r'\bsorry\b',
    r'\blet me rephrase\b',
    r'\bactually\b',
    r'\bwhat i meant\b',
    r'\bi meant\b',
]

# K1: top 1000 most frequent English words (BNC/COCA, lemmatized)
# Simplified representative set — production version would use full list
_K1_WORDS: set[str] = {
    'the',
    'be',
    'to',
    'of',
    'and',
    'a',
    'in',
    'that',
    'have',
    'i',
    'it',
    'for',
    'not',
    'on',
    'with',
    'he',
    'as',
    'you',
    'do',
    'at',
    'this',
    'but',
    'his',
    'by',
    'from',
    'they',
    'we',
    'say',
    'her',
    'she',
    'or',
    'an',
    'will',
    'my',
    'one',
    'all',
    'would',
    'there',
    'their',
    'what',
    'so',
    'up',
    'out',
    'if',
    'about',
    'who',
    'get',
    'which',
    'go',
    'me',
    'when',
    'make',
    'can',
    'like',
    'time',
    'no',
    'just',
    'him',
    'know',
    'take',
    'people',
    'into',
    'year',
    'your',
    'good',
    'some',
    'could',
    'them',
    'see',
    'other',
    'than',
    'then',
    'now',
    'look',
    'only',
    'come',
    'its',
    'over',
    'think',
    'also',
    'back',
    'after',
    'use',
    'two',
    'how',
    'our',
    'work',
    'first',
    'well',
    'way',
    'even',
    'new',
    'want',
    'because',
    'any',
    'these',
    'give',
    'day',
    'most',
    'us',
    'great',
    'find',
    'here',
    'thing',
    'many',
    'still',
    'long',
    'own',
    'need',
    'tell',
    'much',
    'should',
    'may',
    'very',
    'where',
    'help',
    'through',
    'world',
    'each',
    'life',
    'old',
    'more',
    'hand',
    'high',
    'place',
    'last',
    'same',
    'begin',
    'while',
    'must',
    'home',
    'big',
    'end',
    'too',
    'right',
    'call',
    'small',
    'man',
    'woman',
    'run',
    'put',
    'read',
    'turn',
    'keep',
    'try',
    'let',
    'never',
    'off',
    'again',
    'every',
    'ask',
    'follow',
    'show',
    'start',
    'change',
    'move',
    'play',
    'leave',
    'close',
    'stop',
    'open',
    'seem',
    'next',
    'walk',
    'water',
    'eat',
    'food',
    'school',
    'house',
    'city',
    'family',
    'head',
    'stand',
    'child',
    'point',
    'number',
    'group',
    'problem',
    'fact',
    'sit',
    'hold',
    'country',
    'part',
    'name',
    'live',
    'might',
    'always',
    'buy',
    'pay',
    'really',
    'few',
    'already',
    'car',
    'before',
    'between',
    'down',
    'around',
    'little',
    'another',
    'under',
    'quite',
    'far',
    'both',
    'enough',
    'side',
    'night',
    'write',
    'become',
    'money',
    'grow',
    'love',
    'set',
    'against',
    'early',
    'away',
    'since',
    'without',
    'bring',
    'air',
    'door',
    'line',
    'friend',
    'face',
    'wait',
    'morning',
    'ago',
    'meet',
    'along',
    'yet',
    'idea',
    'eye',
    'nothing',
    'drive',
    'book',
    'word',
    'sure',
    'room',
    'body',
    'second',
    'watch',
    'often',
    'store',
    'rain',
    'heavy',
    'decide',
    'bus',
    'crowd',
    'vegetable',
    'fruit',
    'soup',
    'realize',
    'forget',
    'milk',
    'trip',
    'fast',
    'annoy',
    'area',
    'nice',
    'overall',
    'productive',
    'tire',
    'shop',
    'dog',
    'cat',
    'garden',
    'mat',
    'sat',
    'yesterday',
    'today',
    'tomorrow',
    'went',
    'gone',
    'week',
    'month',
    'weather',
    'enjoy',
    'happy',
    'bad',
    'hard',
    'easy',
    'learn',
    'study',
    'speak',
    'language',
    'practice',
    'different',
    'native',
    'improve',
    'rule',
    'focus',
    'value',
    'important',
    'material',
    'movie',
    'neighbor',
    'restaurant',
    'had',
    'was',
    'been',
    'did',
    'got',
    'made',
    'took',
    'came',
    'said',
    'thought',
    'saw',
    'knew',
    'gave',
    'found',
    'told',
    'felt',
    'left',
    'hear',
}

# K2: words ranked 1001-2000 (representative subset)
_K2_WORDS: set[str] = {
    'accept',
    'achieve',
    'add',
    'admire',
    'admit',
    'adopt',
    'advance',
    'advantage',
    'adventure',
    'afford',
    'agree',
    'aim',
    'allow',
    'announce',
    'apart',
    'appear',
    'apply',
    'approach',
    'approve',
    'argue',
    'arrange',
    'arrive',
    'attempt',
    'attend',
    'attract',
    'avoid',
    'aware',
    'balance',
    'base',
    'battle',
    'beat',
    'beauty',
    'belong',
    'bend',
    'beside',
    'beyond',
    'bite',
    'blame',
    'block',
    'blow',
    'board',
    'bore',
    'bottom',
    'brain',
    'brave',
    'break',
    'breath',
    'bright',
    'broad',
    'burn',
    'bury',
    'calm',
    'camp',
    'capable',
    'capture',
    'care',
    'carry',
    'catch',
    'cause',
    'celebrate',
    'central',
    'century',
    'certain',
    'challenge',
    'character',
    'charge',
    'cheap',
    'check',
    'choice',
    'circle',
    'claim',
    'clean',
    'clear',
    'climb',
    'cloud',
    'collect',
    'comfort',
    'command',
    'common',
    'compare',
    'complete',
    'concern',
    'condition',
    'connect',
    'consider',
    'contain',
    'continue',
    'control',
    'copy',
    'corner',
    'correct',
    'cost',
    'count',
    'couple',
    'courage',
    'cover',
    'cross',
    'crowd',
    'cry',
    'cup',
    'cure',
    'curious',
    'current',
    'cut',
    'damage',
    'danger',
    'dare',
    'dark',
    'deal',
    'deep',
    'defeat',
    'defend',
    'degree',
    'deliver',
    'demand',
    'depend',
    'describe',
    'design',
    'desire',
    'destroy',
    'develop',
    'die',
    'direct',
    'disappear',
    'discover',
    'discuss',
    'disease',
    'display',
    'distance',
    'divide',
    'double',
    'doubt',
    'draw',
    'dream',
    'dress',
    'drink',
    'drop',
    'dry',
    'dust',
    'duty',
    'earn',
    'edge',
    'education',
    'effect',
    'effort',
    'election',
    'empty',
    'enemy',
    'energy',
    'engage',
    'engine',
    'enjoy',
    'enter',
    'environment',
    'equal',
    'escape',
    'examine',
    'example',
    'exchange',
    'excite',
    'exercise',
    'exist',
    'expect',
    'experience',
    'experiment',
    'explain',
    'explore',
    'express',
    'extend',
    'extra',
    'extreme',
    'fail',
    'fair',
    'fall',
    'false',
    'familiar',
    'fear',
    'feature',
    'feed',
    'fill',
    'final',
    'finger',
    'finish',
    'fire',
    'fit',
    'fix',
    'flat',
    'flight',
    'float',
    'floor',
    'flow',
    'fly',
    'force',
    'foreign',
    'form',
    'forward',
    'free',
    'fresh',
    'front',
    'fruit',
    'fuel',
    'full',
    'fun',
    'future',
    'gain',
    'gather',
    'general',
    'gentle',
    'gift',
    'glad',
    'gold',
    'government',
    'grab',
    'grade',
    'grain',
    'grand',
    'guard',
    'guess',
    'guide',
    'hang',
    'happen',
    'harm',
    'hat',
    'hate',
}

# AWL: Academic Word List (570 word families, representative subset)
_AWL_WORDS: set[str] = {
    'analyze',
    'analyse',
    'approach',
    'area',
    'assess',
    'assume',
    'authority',
    'available',
    'benefit',
    'concept',
    'consist',
    'constitute',
    'context',
    'contract',
    'create',
    'data',
    'define',
    'derive',
    'distribute',
    'economy',
    'environment',
    'establish',
    'estimate',
    'evident',
    'export',
    'factor',
    'finance',
    'formula',
    'function',
    'identify',
    'income',
    'indicate',
    'individual',
    'interpret',
    'involve',
    'issue',
    'labour',
    'legal',
    'legislate',
    'major',
    'method',
    'occur',
    'percent',
    'period',
    'policy',
    'principle',
    'proceed',
    'process',
    'require',
    'research',
    'respond',
    'role',
    'section',
    'sector',
    'significant',
    'similar',
    'source',
    'specific',
    'structure',
    'theory',
    'vary',
    'achieve',
    'acquire',
    'administrate',
    'affect',
    'appropriate',
    'aspect',
    'assist',
    'category',
    'chapter',
    'commission',
    'community',
    'complex',
    'compute',
    'conclude',
    'conduct',
    'consequent',
    'construct',
    'consume',
    'credit',
    'culture',
    'design',
    'distinct',
    'element',
    'equate',
    'evaluate',
    'feature',
    'final',
    'focus',
    'impact',
    'injure',
    'institute',
    'invest',
    'item',
    'journal',
    'maintain',
    'normal',
    'obtain',
    'participate',
    'perceive',
    'positive',
    'potential',
    'previous',
    'primary',
    'purchase',
    'range',
    'region',
    'regulate',
    'relevant',
    'reside',
    'resource',
    'restrict',
    'secure',
    'seek',
    'select',
    'site',
    'strategy',
    'survey',
    'text',
    'tradition',
    'transfer',
    'comprehensive',
    'contribute',
    'corporate',
    'correspond',
    'criteria',
    'deduce',
    'demonstrate',
    'document',
    'dominate',
    'emphasis',
    'ensure',
    'exclude',
    'framework',
    'fund',
    'illustrate',
    'immigrate',
    'imply',
    'initial',
    'instance',
    'interact',
    'justify',
    'layer',
    'link',
    'locate',
    'maximize',
    'minor',
    'negate',
    'outcome',
    'partner',
    'philosophy',
    'physical',
    'proportion',
    'publish',
    'react',
    'register',
    'rely',
    'remove',
    'scheme',
    'sequence',
    'shift',
    'specify',
    'sufficient',
    'task',
    'technical',
    'technique',
    'technology',
    'valid',
    'volume',
    'hypothesis',
    'methodology',
    'empirical',
    'correlation',
    'substantial',
    'theoretical',
    'conceptual',
    'implications',
    'rigorous',
    'linguistic',
    'pragmatic',
    'nuanced',
}

_CONJUNCTION_MARKERS = {
    'however',
    'therefore',
    'moreover',
    'furthermore',
    'nevertheless',
    'although',
    'because',
    'since',
    'while',
    'whereas',
    'meanwhile',
    'consequently',
    'thus',
    'hence',
    'accordingly',
    'besides',
    'nonetheless',
    'so',
    'but',
    'and',
    'or',
    'yet',
    'for',
    'nor',
}

_SUBORDINATE_MARKERS = {'mark', 'advcl', 'ccomp', 'xcomp', 'acl', 'relcl'}

_TENSE_TAG_MAP = {
    'VBD': 'past_simple',
    'VBN': 'past_participle',
    'VBG': 'present_participle',
    'VBZ': 'present_3sg',
    'VBP': 'present_non3sg',
    'VB': 'base',
    'MD': 'modal',
}


class NlpAnalyzer:
    def __init__(self, nlp: Language | None = None) -> None:
        self._nlp = nlp or spacy.load('en_core_web_sm')

    def analyze(self, text: str) -> NlpMetrics:
        if not text.strip():
            return NlpMetrics()

        doc = self._nlp(text)
        tokens = [t.text.lower() for t in doc if t.is_alpha]
        lemmas = [t.lemma_.lower() for t in doc if t.is_alpha]

        # Lexical diversity
        mtld = None
        vocd_d = None
        if len(tokens) >= _MIN_TOKENS_FOR_DIVERSITY:
            mtld = float(lex_div.mtld(tokens))
            vocd_d = float(lex_div.hdd(tokens))

        # Word frequency distribution
        total = len(lemmas) if lemmas else 1
        k1_count = sum(1 for w in lemmas if w in _K1_WORDS)
        k2_count = sum(1 for w in lemmas if w in _K2_WORDS and w not in _K1_WORDS)
        awl_count = sum(
            1 for w in lemmas if w in _AWL_WORDS and w not in _K1_WORDS and w not in _K2_WORDS
        )
        k1_ratio = k1_count / total
        k2_ratio = k2_count / total
        awl_ratio = awl_count / total

        # Sentence-level metrics
        sentences = list(doc.sents)
        num_sents = len(sentences) if sentences else 1
        avg_sentence_length = len(tokens) / num_sents

        # Conjunction ratio
        conj_count = sum(1 for t in doc if t.text.lower() in _CONJUNCTION_MARKERS)
        conjunction_ratio = conj_count / num_sents

        # Self-correction detection
        text_lower = text.lower()
        self_correction_count = sum(
            len(re.findall(pattern, text_lower)) for pattern in _SELF_CORRECTION_PATTERNS
        )

        # Subordinate clause ratio
        sub_count = sum(1 for t in doc if t.dep_ in _SUBORDINATE_MARKERS)
        subordinate_clause_ratio = sub_count / num_sents

        # Tense diversity
        tenses = {_TENSE_TAG_MAP[t.tag_] for t in doc if t.tag_ in _TENSE_TAG_MAP}
        tense_diversity = len(tenses)

        # Grammar error count (basic: spaCy doesn't do grammar checking,
        # count tokens with no valid POS as proxy)
        grammar_error_count = sum(1 for t in doc if t.is_alpha and t.pos_ == 'X')

        # Clamp ratios to [0, 1]
        conjunction_ratio = min(conjunction_ratio, 1.0)
        subordinate_clause_ratio = min(subordinate_clause_ratio, 1.0)

        return NlpMetrics(
            mtld=mtld,
            vocd_d=vocd_d,
            k1_ratio=k1_ratio,
            k2_ratio=k2_ratio,
            awl_ratio=awl_ratio,
            avg_sentence_length=avg_sentence_length,
            conjunction_ratio=conjunction_ratio,
            self_correction_count=self_correction_count,
            subordinate_clause_ratio=subordinate_clause_ratio,
            tense_diversity=tense_diversity,
            grammar_error_count=grammar_error_count,
        )
